title: "Faith Tabernacle Church"
description: "A Bible-believing church in Liberal, Kansas glorifying God and loving our community."

url: "https://faithtabliberal.org"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  sermons:
    output: true
    permalink: /sermons/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "sermons"
    values:
      layout: sermon-post

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
